### ISSUE TITLE
Add deployment to Travis

### ISSUE THREAD

**Issue by aaronmallen** [dhiemstra/esi#17]
In order to stabilize releases discussed in #11 we will need to deploy to rubygems via travis.

@dhiemstra please add the following to `.travis.yml`

```yaml
deploy:
  provider: rubygems
  on:
    branch: master
    tags: true
```

and then install the travis gem and run the following:
```
gem install travis
travis encrypt <YOUR RUBY GEMS API KEY> --add deploy.api_key
```

Then a new version of the gem will only be released to ruby gems when we create a new release via tags. This means we will no longer deploy the gem manually but our releases will be less frequent and more stable.
